name: BuildOnPush

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    if: github.repository != 'intel/trustauthority-client-for-go'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: main
          path: client-go
          fetch-depth: 0
      
      - name: Setup Go Env
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.23.6'

      - name: build tdx-cli
        run: |
          cd client-go/tdx-cli
          make cli

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-go-${{ github.run_number }}
          path: client-go/tdx-cli/trustauthority-cli
